### ISSUE TITLE
File system stuck in read-only

### ISSUE THREAD

**Issue by russlamb** [Landmaj/Raspi_Backup#1]
I ran the script but on reboot my file system is in read-only mode.  Cannot run script again because file system is read only.

**Comment by russlamb** [comment]
Found a solution.

1. remount root in read-write mode: sudo mount -o remount,rw /
2. edit /etc/fstab to remove "ro," where they occur
3. reboot

**Comment by landmaj** [comment]
If after using the script your filesystem is still read only, there had to be an error and hopefully some information in log. Using the same backup script with a 'cleanup' parameter should solve the problem and it is the recommended way as it will remove script that starts backup after boot. You can also remove this init.d script with:
`rm /etc/init.d/rpibackup`
`update-rc.d -f rpibackup remove`
And you should probably do it before you reboot the system.
